/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_dr_testappdemo_DR_JNITest */

#ifndef _Included_dr_dr_testappdemo_DR_JNITest
#define _Included_dr_dr_testappdemo_DR_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dr_dr_testappdemo_DR_JNITest
 * Method:    getSuccessKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_umeng_soexample_JNITest_getSuccessKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif

void sub_0329(JNIEnv* env);
#endif

